spring:
  application:
    name: nacos-discovery-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          name: lengleng
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"